#!/bin/bash -e

get_crate_name()
{
  while [[ $# -gt 1 ]] ; do
    v=$1
    case $v in
      --crate-name)
        echo $2
        return
        ;;
    esac
    shift
  done
}

case $(get_crate_name "$@") in
    mesabox|tests)
    EXTRA=$COVERAGE_OPTIONS
    ;;
  *)
    EXTRA=$OPTIONS
    ;;
esac

exec "$@" $EXTRA
